### ISSUE TITLE
Antwortet dieser Bot auch auf Gruppen?

### ISSUE THREAD

**Issue by janves** [Myzel394/whatsapp_switch_to_signal#1]
Das wäre meine Frage, bevor ich ihn aktivieren würde, da mir das sehr unangenehm wäre.

**Comment by Myzel394** [comment]
Er antwortet privat auf die Person. Ich arbeite gerade an einem Update.

**Comment by janves** [comment]
Ah okay, dann warte ich Mal besser, bis das gelöst ist. Viel Erfolg 👍

**Comment by Myzel394** [comment]
Ok ist jetzt hinzugefügt, du kannst `settings.py` Einstellungen vornehmen. `REPLY_TO_GROUP_WHEN_MENTIONED` funktioniert noch nicht - Vielleicht weiß ja jemand, wie man die ID des aktuellen Benutzers herausfinden kann.
